In [2]:
from sklearn.datasets import load_boston
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd 

In [3]:
boston=load_boston()

In [4]:
boston['data']

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [6]:
x_data=boston.data
y_data=boston.target.reshape(boston.target.size,1)

In [7]:
y_data.shape

(506, 1)

In [8]:
from sklearn import preprocessing

In [9]:
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0,5)).fit(x_data)
# standard_scale = preprocessing.StandardScaler().fit(x_data)
x_scaled_data = minmax_scale.transform(x_data)
x_scaled_data[:3]

array([[0.00000000e+00, 9.00000000e-01, 3.39076246e-01, 0.00000000e+00,
        1.57407407e+00, 2.88752635e+00, 3.20803296e+00, 1.34601570e+00,
        0.00000000e+00, 1.04007634e+00, 1.43617021e+00, 5.00000000e+00,
        4.48399558e-01],
       [1.17961270e-03, 0.00000000e+00, 1.21151026e+00, 0.00000000e+00,
        8.64197531e-01, 2.73998850e+00, 3.91349125e+00, 1.74480990e+00,
        2.17391304e-01, 5.24809160e-01, 2.76595745e+00, 5.00000000e+00,
        1.02235099e+00],
       [1.17848872e-03, 0.00000000e+00, 1.21151026e+00, 0.00000000e+00,
        8.64197531e-01, 3.47192949e+00, 2.99691040e+00, 1.74480990e+00,
        2.17391304e-01, 5.24809160e-01, 2.76595745e+00, 4.94868627e+00,
        3.17328918e-01]])

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(x_scaled_data, y_data, test_size=0.3)

In [13]:
from sklearn import linear_model

In [14]:
regr=linear_model.LinearRegression(fit_intercept=True, normalize=False,
                                  copy_X=True, n_jobs=8)

In [16]:
regr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=8, normalize=False)

In [17]:
regr

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=8, normalize=False)

In [18]:
regr.coef_

array([[-2.35358519,  0.81651641,  0.1102699 ,  0.72495435, -1.95683801,
         3.37762939,  0.16233448, -2.99839798,  1.41755833, -0.98508575,
        -1.839501  ,  0.84344662, -3.8706132 ]])

In [19]:
regr.intercept_

array([26.99060531])

In [20]:
regr.predict(x_data[:5])

array([[ 58.5797655 ],
       [ 77.47859271],
       [ 93.51560056],
       [111.78796452],
       [106.23236972]])

In [21]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [22]:
y_true = y_test
y_hat = regr.predict(X_test)

In [23]:
r2_score(y_true, y_hat), mean_absolute_error(y_true, y_hat), mean_squared_error(y_true,y_hat)

(0.749240728310784, 3.5870829110934097, 24.86436683317437)

In [24]:
y_true = y_train
y_hat = regr.predict(X_train)

In [25]:
r2_score(y_true, y_hat), mean_absolute_error(y_true, y_hat), mean_squared_error(y_true, y_hat)

(0.7292676386998828, 3.201638927963504, 21.074597968299322)

In [26]:
regr.score(X_test, y_test)

0.749240728310784